# Workflow
# Should have name
name: Hello

on:
  workflow_dispatch:
  
# Jobs
#should be inside the workflow
Jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
        - name: Say hello to everyone
        run: echo "hello dosto"

# Steps
# should inside the job

# Actions
# should be in the steps
